<a href="https://colab.research.google.com/github/jhee-yun/test_python/blob/main/python_language.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
np.__version__

'1.19.5'

In [39]:
def onehotcylinder(cylinders):
  if cylinders == 3:
    cylinder = np.array([1,0,0,0,0])
  elif cylinders == 4:
    cylinder = np.array([0,1,0,0,0])
  elif cylinders == 5:
    cylinder = np.array([0,0,1,0,0])
  elif cylinders == 6:
    cylinder = np.array([0,0,0,1,0])
  else :
    cylinder = np.array([0,0,0,0,1])
  return cylinder

In [44]:
displacement = 307.0
horsepower = 130.0
weight = 3504.0
accel = 12.0
cylinders = 8
origin = 1

# if cylinders = 8, origin = 1 -> onehot encoding

import numpy as np

if cylinders == 3:
  cylinder = np.array([1,0,0,0,0])
elif cylinders == 4:
  cylinder = np.array([0,1,0,0,0])
elif cylinders == 5:
  cylinder = np.array([0,0,1,0,0])
elif cylinders == 6:
  cylinder = np.array([0,0,0,1,0])
else :
  cylinder = np.array([0,0,0,0,1])


x_continus = np.array([displacement, horsepower, weight, accel])
# cylinder = np.array([0,0,0,0,1])
cylinder = onehotcylinder(cylinders)
org = np.array([1,0,0])

In [43]:
onehotcylinder(4), onehotcylinder(6)

(array([0, 1, 0, 0, 0]), array([0, 0, 0, 1, 0]))

In [16]:
cylinder

array([0, 0, 0, 0, 1])

In [7]:
# type(x_continus), type(cylinder), type(org)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [45]:
# np.concatenate((a, b), axis=None)
result = np.concatenate((x_continus, cylinder, org), axis=None)
result.shape, result

((12,),
 array([3.070e+02, 1.300e+02, 3.504e+03, 1.200e+01, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 1.000e+00, 1.000e+00, 0.000e+00, 0.000e+00]))

In [46]:
#[307.0,130.0,3504.0,12.0,0,0,0,0,1,1,0,0]
#result.reshape(1,12) 
result = result.reshape(-1, result.size)
result, result.shape

(array([[3.070e+02, 1.300e+02, 3.504e+03, 1.200e+01, 0.000e+00, 0.000e+00,
         0.000e+00, 0.000e+00, 1.000e+00, 1.000e+00, 0.000e+00, 0.000e+00]]),
 (1, 12))

In [19]:
result.size, result

(12, array([[3.070e+02, 1.300e+02, 3.504e+03, 1.200e+01, 0.000e+00, 0.000e+00,
         0.000e+00, 0.000e+00, 1.000e+00, 1.000e+00, 0.000e+00, 0.000e+00]]))

## function 이해

In [20]:
21 + 14

35

In [21]:
32+45

77

In [25]:
def sum():
  first = 21
  second = 14
  result = first + second
  return result

In [28]:
sum()

35

In [29]:
def sum(f01,s01):
  first = f01
  second = s01
  result = first + second
  return result

In [31]:
sum(32,21), sum(3,2), sum(21,564)

(53, 5, 585)

In [33]:
def multi(a1,b1,c1):
  a = a1
  b = b1
  c = c1
  result = a * b * c
  return result

In [34]:
multi(6,9,5)

270

In [36]:
# def differenceVars(*var01, **args02)
def diffparam(*var_list, **var_dict):
  print(var_dict)
  result01 = len(var_list)
  return result01

In [38]:
diffparam(1,2,3,5,6, c=5, d=6, a=2,b=3)

{'c': 5, 'd': 6, 'a': 2, 'b': 3}


5